### PR TITLE
fixed small errors

### PR DESCRIPTION
**Pull request by 0xflotus**
I only fixed two small typo errors

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=10) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=10) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Hippy?pullRequest=10) it.</sub>

**Comment by xuqingkuang** [comment]
Thanks a lot for your PR, please take care of the commit message guideline.

We are using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by 0xflotus** [comment]
Ah I see. Ok how can I change it?

**Comment by xuqingkuang** [comment]
> Ah I see. Ok how can I change it?

The simplest way is `git reset --soft HEAD^`, and commit again, then `git push -f`.

Pull request will automatical update, no more operations needs.

**Comment by xuqingkuang** [comment]
Sorry, as long time no response, I have to fix the typo in another commit.

Thank you for your contribution, please keep going on.

**Pull request closed without merging**
