### PR TITLE
Fixes a typo in Xcode

### PR DESCRIPTION
**Pull request by steipete**
This PR fixes a small typo in Xcode. CLA signed.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=26) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=26) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Hippy?pullRequest=26) it.</sub>

**Comment by xuqingkuang** [comment]
Hi, thank you for your patch.

Please take care of the commit message, Hippy is following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) guideline.

BTW: Could you check more typo mistakes and make a submission?

**Comment by steipete** [comment]
Interesting. I've renamed the commit message to conform to the guideline.

I did search for any other cases of Xcode spelling but looks like everywhere else you got it right. Thanks!

**Comment by xuqingkuang** [comment]
Sorry, it's fixed in #28, I have to close the PR.

**Comment by steipete** [comment]
Well, that‘s disappointing.

**Pull request closed without merging**
