### PR TITLE
feat(publish): use fat-aar-android to build aar

### PR DESCRIPTION
**Pull request by siguangli**
# Pre-PR Checklist

- [x] I added/updated relevant documentation.
- [x] I followed the [Convention Commit](https://conventionalcommits.org/) guideline with maximum 72 characters to submit commit message.
- [x] I squashed the repeated code commits.
- [x] I signed the [CLA].
- [x] I added/updated test cases to check the change I am making.
- [x] All existing and new tests are passing.

### CODE REVIEW

**Review by medns — CHANGES_REQUESTED** [review]
contact me

**Review by medns — CHANGES_REQUESTED** [review]
Need changes

**Review by zoomchan-cxj — DISMISSED** [review]
LGTM

**Review by medns — CHANGES_REQUESTED** [review]
Change to static gradle deps

**Review by medns — APPROVED** [review]
LGTM

**Pull request merged**
