### PR TITLE
fix: correct minor typos in README.zh_CN

### PR DESCRIPTION
**Pull request by twiceyuan**
规范标点

Before submitting a new pull request, please make sure:

- [x] Test cases have been added/updated for the code you will submit.
- [x] Documentation has added or updated.
- [x] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline.
- [x] Squash the repeat code commits, short patches are welcome.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=44) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=44) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Hippy?pullRequest=44) it.</sub>

**Comment by xuqingkuang** [comment]
好希望 README 的问题能一次性改完哦。

不过你也注意一下提交 PR 时的四个注意事项，缺一不可，现在自动代码检查出问题了，是 commit message 不规范。

**Comment by xuqingkuang** [comment]
要改 commit message 了，不是 Pull request 的标题。。。

**Comment by xuqingkuang** [comment]
fixed in #96

**Pull request closed without merging**
