### PR TITLE
删除多余的'啊'字

### PR DESCRIPTION
**Pull request by nayonglin**
Before submitting a new pull request, please make sure:

- [x] Test cases have been added/updated for the code you will submit.
- [x] Documentation has added or updated.
- [x] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline.
- [x] Squash the repeat code commits, short patches are welcome.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=35) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/Hippy?pullRequest=35) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/Hippy?pullRequest=35) it.</sub>

**Comment by fangge** [comment]
秀儿~

**Comment by xuqingkuang** [comment]
commit message 有问题，改一改吧。 ;-)

git reset --soft HEAD^
git commit -am 'chore(doc): Removed unnecessary characters in README'
git push -f

**Comment by BeanWei** [comment]
> 秀儿~

+1

**Comment by xuqingkuang** [comment]
fixed in #96

**Pull request closed without merging**
