### PR TITLE
refactor(android): migrate SDK to new version and temporarily disable NDK

### PR DESCRIPTION
**Pull request by kassadin**
migrate SDK to new version, Ndk is no longer needed to run the android demo.

1. gradle 5.5.1
2. android plugin 3.5.3
3. target api 29
4. androidX

remove all ndk task

BREAKING CHANGE: Disable ndk temporarily and wait for migration to
new version. Delete all ndk history tasks, including internal CI, zip,
QB? backup, etc.These may need to be redone.

Before submitting a new pull request, please make sure:

- [x] Test cases have been added/updated for the code you will submit.
- [x] Documentation has added or updated.
- [x] Commit message is following the [Convention Commit](https://conventionalcommits.org/) guideline.
- [x] Squash the repeat code commits, short patches are welcome.

### CODE REVIEW

**Comment by xuqingkuang** [comment]
NDK should not be disabled, because of part of Hippy is written with C++.

**Comment by kassadin** [comment]
> NDK should not be disabled, because of part of Hippy is written with C++.

是临时屏蔽，native 部分的环境太旧了，很多人都跑不起来 demo，而且 libs 下是有已编译好的 so 的。

可以等 native 环境更新、发布 maven 后再加回到 sdk 中。

**Comment by xuqingkuang** [comment]
> > NDK should not be disabled, because of part of Hippy is written with C++.
> 
> 是临时屏蔽，native 部分的环境太旧了，很多人都跑不起来 demo，而且 libs 下是有已编译好的 so 的。
> 
> 可以等 native 环境更新、发布 maven 后再加回到 sdk 中。

其实还是偏好能搞定 NDK 编译，要不然始终不完整。

**Comment by kassadin** [comment]
那你们内部是怎么规划这块呢？现在还有人负责这块么？

**Comment by xuqingkuang** [comment]
> 那你们内部是怎么规划这块呢？现在还有人负责这块么？

siguangli 是负责 Android 客户端的，不过他很忙，又要忙业务又要改框架，升级 toolchain 优先级可能没那么高。

**Comment by fsxiaoke** [comment]
> > NDK should not be disabled, because of part of Hippy is written with C++.
> 
> 是临时屏蔽，native 部分的环境太旧了，很多人都跑不起来 demo，而且 libs 下是有已编译好的 so 的。
> 
> 可以等 native 环境更新、发布 maven 后再加回到 sdk 中。

nkd需要version 20，同时禁用lint报错，就能编译过了

**Comment by xuqingkuang** [comment]
The patch is not acceptable so far, please continue to make more contribution, thanks a lot.

Close it.

**Pull request closed without merging**
